In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as pdr
import seaborn as sns
import talib 
from sklearn.preprocessing import MinMaxScaler
from sklearn import tree
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.model_selection import train_test_split


In [4]:
startdate = '2016-01-1'
enddate= '2021-12-31'
scaler = MinMaxScaler()

In [5]:
dji = pdr.get_data_yahoo('^DJI', start=startdate, end=enddate)
dji_norm = pd.DataFrame(scaler.fit_transform(dji), columns=dji.columns)
n225 = pdr.get_data_yahoo("^N225", start=startdate, end=enddate)
n225_norm = pd.DataFrame(scaler.fit_transform(n225), columns=n225.columns)
hsi = pdr.get_data_yahoo("^HSI", start=startdate, end=enddate)
hsi_norm = pd.DataFrame(scaler.fit_transform(hsi), columns=hsi.columns)
sse = pdr.get_data_yahoo("000001.SS", start=startdate, end=enddate)
sse_norm = pd.DataFrame(scaler.fit_transform(sse), columns=sse.columns)


<h1>Dow Jones Industrial Average</h1>

<h2>Feature Selection</h2>

In [6]:
dji['Future Close'] = dji['Close'].shift(-1)
dji

High           Low          Open         Close     Volume  \
Date                                                                            
2015-12-31  17590.660156  17421.160156  17590.660156  17425.029297   93690000   
2016-01-04  17405.480469  16957.630859  17405.480469  17148.939453  148060000   
2016-01-05  17195.839844  17038.609375  17147.500000  17158.660156  105750000   
2016-01-06  17154.830078  16817.619141  17154.830078  16906.509766  120250000   
2016-01-07  16888.359375  16463.630859  16888.359375  16514.099609  176240000   
...                  ...           ...           ...           ...        ...   
2021-11-18  35952.628906  35654.390625  35901.691406  35870.949219  435080000   
2021-11-19  35879.089844  35555.371094  35879.089844  35601.980469  408840000   
2021-11-22  35929.660156  35615.550781  35631.410156  35619.250000  420810000   
2021-11-23  35841.519531  35542.871094  35619.921875  35813.800781  392520000   
2021-11-24  35825.468750  35591.031250  35752.308594  35804.378906  280960000   

               Adj Close  Future Close  
Date                                    
2015-12-31  17425.029297  17148.939453  
2016-01-04  17148.939453  17158.660156  
2016-01-05  17158.660156  16906.509766  
2016-01-06  16906.509766  16514.099609  
2016-01-07  16514.099609  16346.450195  
...                  ...           ...  
2021-11-18  35870.949219  35601.980469  
2021-11-19  35601.980469  35619.250000  
2021-11-22  35619.250000  35813.800781  
2021-11-23  35813.800781  35804.378906  
2021-11-24  35804.378906           NaN  

[1487 rows x 7 columns]

In [7]:
def computeTarget(present_price, future_price):
    score = (( future_price - present_price ) / present_price ) * 100
    target = []
    for i in score:
        if i > 0:
            target.append(1)
        else:
            target.append(0)
    return target
# 2 = up, 1 = down, 0 = sideway

In [8]:

target = computeTarget(dji['Close'], dji['Future Close'])

dji['Target'] = target
dji = dji.dropna()

In [9]:
close = dji['Close']
high = dji['High']
low = dji['Low']
open = dji['Open']
volume  = dji['Volume']

In [10]:
dji_ti = pd.DataFrame()

In [11]:

dji_ti['SMA20'] = talib.SMA(close, timeperiod=20)
dji_ti['SMA50'] = talib.SMA(close, timeperiod=50)
dji_ti['SMA200'] = talib.SMA(close, timeperiod=200)
dji_ti['EMA'] = talib.EMA(close, timeperiod=14)
dji_ti['OBV'] = talib.OBV(close, volume)
dji_ti['RSI14'] = talib.RSI(close, timeperiod=14)
dji_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
dji_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
dji_ti['aroondown'], dji_ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
dji_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
dji_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
dji_ti['BOP'] = talib.BOP(open, high, low, close)
dji_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
dji_ti['CMO'] = talib.CMO(close, timeperiod=14)
dji_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
dji_ti['macd'],dji_ti['macdsignal'],dji_ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
dji_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
dji_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
dji_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
dji_ti['MOM'] = talib.MOM(close, timeperiod=14)
dji_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
dji_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
dji_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
dji_ti['ROC'] = talib.ROC(close, timeperiod=10)
dji_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
dji_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
dji_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
dji_ti['slowk'], dji_ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
dji_ti['fastk'], dji_ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
dji_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
dji_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
dji_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
dji_ti['Target'] = dji['Target']
dji_ti

SMA20         SMA50        SMA200           EMA  \
Date                                                                 
2015-12-31           NaN           NaN           NaN           NaN   
2016-01-04           NaN           NaN           NaN           NaN   
2016-01-05           NaN           NaN           NaN           NaN   
2016-01-06           NaN           NaN           NaN           NaN   
2016-01-07           NaN           NaN           NaN           NaN   
...                  ...           ...           ...           ...   
2021-11-17  35970.474023  35159.136719  34186.828047  35994.581955   
2021-11-18  35983.867578  35178.968125  34210.903496  35978.097590   
2021-11-19  35980.115625  35198.853359  34233.172197  35927.948641   
2021-11-22  35974.020703  35213.845781  34254.339648  35886.788822   
2021-11-23  35976.866797  35238.570391  34276.529502  35877.057083   

                     OBV      RSI14        ADX       ADXR   aroondown  \
Date                                                                    
2015-12-31  9.369000e+07        NaN        NaN        NaN         NaN   
2016-01-04 -5.437000e+07        NaN        NaN        NaN         NaN   
2016-01-05  5.138000e+07        NaN        NaN        NaN         NaN   
2016-01-06 -6.887000e+07        NaN        NaN        NaN         NaN   
2016-01-07 -2.451100e+08        NaN        NaN        NaN         NaN   
...                  ...        ...        ...        ...         ...   
2021-11-17  4.032646e+10  54.656278  23.134882  22.278214    0.000000   
2021-11-18  3.989138e+10  53.009423  21.616344  21.578782    0.000000   
2021-11-19  3.948254e+10  46.287684  20.569966  21.215418  100.000000   
2021-11-22  3.990335e+10  46.754531  19.386325  20.889122   92.857143   
2021-11-23  4.029587e+10  51.833578  18.569595  20.727316  100.000000   

              aroonup  ...      ROCR    ROCR100      slowk      slowd  \
Date                   ...                                              
2015-12-31        NaN  ...       NaN        NaN        NaN        NaN   
2016-01-04        NaN  ...       NaN        NaN        NaN        NaN   
2016-01-05        NaN  ...       NaN        NaN        NaN        NaN   
2016-01-06        NaN  ...       NaN        NaN        NaN        NaN   
2016-01-07        NaN  ...       NaN        NaN        NaN        NaN   
...               ...  ...       ...        ...        ...        ...   
2021-11-17  50.000000  ...  0.993735  99.373500  30.743867  30.143858   
2021-11-18  42.857143  ...  0.992989  99.298860  30.205023  33.136388   
2021-11-19  35.714286  ...  0.980016  98.001625  14.707654  25.218848   
2021-11-22  28.571429  ...  0.977685  97.768544  15.738752  20.217143   
2021-11-23  21.428571  ...  0.986063  98.606333  19.479109  16.641838   

                fastk      fastd      TRIX     ULTOSC      WILLR  Target  
Date                                                                      
2015-12-31        NaN        NaN       NaN        NaN        NaN       0  
2016-01-04        NaN        NaN       NaN        NaN        NaN       1  
2016-01-05        NaN        NaN       NaN        NaN        NaN       0  
2016-01-06        NaN        NaN       NaN        NaN        NaN       0  
2016-01-07        NaN        NaN       NaN        NaN        NaN       0  
...               ...        ...       ...        ...        ...     ...  
2021-11-17   5.298153  30.743867  0.054180  40.768597 -68.059884       0  
2021-11-18  32.701973  30.205023  0.056254  43.144530 -76.237339       0  
2021-11-19   6.122836  14.707654  0.057744  41.457206 -95.386852       1  
2021-11-22   8.391447  15.738752  0.058735  38.329353 -93.677605       1  
2021-11-23  43.923044  19.479109  0.059440  40.099397 -73.512519       0  

[1486 rows x 38 columns]

In [12]:
# plt.figure(figsize=(12,10))
# cor = ti.corr()
# sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
# plt.show()

In [13]:
# cor_target = abs(cor["Target"])
# features = cor_target[cor_target>0.05]
# features

In [14]:
dji_ti = dji_ti.dropna()
X = dji_ti.drop("Target", axis=1)  # Feature Matrix
y = dji_ti["Target"]               # Target Variable
y

Date
2016-10-14    0
2016-10-17    1
2016-10-18    1
2016-10-19    0
2016-10-20    0
             ..
2021-11-17    0
2021-11-18    0
2021-11-19    1
2021-11-22    1
2021-11-23    0
Name: Target, Length: 1287, dtype: int64

In [15]:
X = X.fillna(0)

In [16]:
#X.isna().sum()

In [17]:
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, n_features_to_select=7)

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)

print(rfe.support_)
print(rfe.ranking_)

[False False False False False  True False False False False False False
  True False  True False False False False False  True False False  True
 False False  True False False  True False False False False False False
 False]
[19 18 30 28 31  1 10  9  6 17 15 16  1 12  1 20 14 13 23 27  1 24 29  1
 22  5  1 26 25  1  8  4 21 11  7  2  3]


In [18]:
# no. of features
#
nof_list = np.arange(1, 13)            
high_score = 0

# Variable to store the optimum features
#
nof = 0           
score_list = []

for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.9, random_state = 0)

    model = LinearRegression()
    rfe = RFE(model, n_features_to_select=nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)

    score = model.score(X_test_rfe,y_test)
    score_list.append(score)

    if(score > high_score):
        high_score = score
        nof = nof_list[n]

print("Optimum number of features: %d" % nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 0
Score with 0 features: 0.000000


In [19]:
cols = list(X.columns)
model = LinearRegression()

# Initializing RFE model
rfe = RFE(model, n_features_to_select=10)             

# Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

# Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_, index = cols)
selected_features_rfe = temp[temp==True].index

print(selected_features_rfe)

Index(['RSI14', 'BOP', 'CMO', 'MINUS_DI', 'PLUS_DI', 'ROC', 'ROCR100', 'slowd',
       'ULTOSC', 'WILLR'],
      dtype='object')


In [20]:
# dji_ti = dji_ti.dropna()
# X = dji_ti.drop("Target", axis=1)  # Feature Matrix
# y = dji_ti["Target"]               # Target Variable
# #Split the features and target data
# #Define Sequential Forward Selection (sfs)
# sfs = SFS(LinearRegression(),
#            k_features=5,
#            forward=True,
#            floating=False,
#            scoring = 'r2',
#            cv = 0)
# #Use SFS to select the top 5 features 
# sfs.fit(X, y)

# #Create a dataframe for the SFS results 
# df_SFS_results = pd.DataFrame(sfs.subsets_).transpose()
# df_SFS_results


<h2>จากการทำ Feature Selection ควรจะใช้ 'RSI14', 'BOP', 'CMO', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC', 'ROCR100','TRIX', 'ULTOSC' ในการสร้าง model</h2>

In [21]:
from sklearn.model_selection import train_test_split
X = dji_ti.loc[:, ['RSI14', 'BOP', 'CMO', 'MINUS_DI', 'PLUS_DI', 'PPO', 'ROC', 'ROCR100','TRIX', 'ULTOSC']].values
#X = dji_ti.loc[:, ['CCI', 'DX', 'MINUS_DI', 'PLUS_DM', 'slowd']].values
y = dji_ti.loc[:, ['Target']].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
y_test

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [24]:
# Visualize the data
#
def visualize(title, xlabel, ylabel, classifier, X_test, y_test):
    X_set, y_set = X_test, y_test
    X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                         np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
    plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
                 alpha = 0.75, cmap = ListedColormap(('lightblue', 'cornsilk')))
    plt.xlim(X1.min(), X1.max())
    plt.ylim(X2.min(), X2.max())

    for i, j in enumerate(np.unique(y_set)):
        plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], label = j)

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.show()

<h2>Decision Tree</h2>

In [25]:
# Decision Tree Classifier: Create and Train the model
#
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [26]:
# Prediction
#
y_pred = dtc.predict(X_test)  #Accuracy
y_pred

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [27]:
# Look at the actual y_test
#
y_test

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [28]:
# See the accuracy
#
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.5310077519379846


In [29]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[50, 53],
       [68, 87]], dtype=int64)

<h2>Random Forest</h2>

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [68]:
forest = RandomForestClassifier(n_estimators = 1000, random_state = 42, max_depth=2)
forest.fit(X_train, y_train)

C:\Users\kjmoo\AppData\Local\Temp/ipykernel_8792/557468781.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest.fit(X_train, y_train)


RandomForestClassifier(max_depth=2, n_estimators=1000, random_state=42)

In [69]:
ypred = forest.predict(X_test)
ypred


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [70]:
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, ypred))

Accuracy Score: 0.6007751937984496


In [71]:
# See the confusion matrix
#
from sklearn.metrics import confusion_matrix
conm = confusion_matrix(y_test, ypred)
conm

array([[  3, 100],
       [  3, 152]], dtype=int64)

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regress</h2>

<h1>Nikkei 225 Stock Average</h1>

<h2>Feature Selection</h2>

In [35]:
n225['Future Close'] = n225['Close'].shift(-1)
n225

High           Low          Open         Close  \
Date                                                                 
2016-01-04  18951.119141  18394.429688  18818.580078  18450.980469   
2016-01-05  18547.380859  18327.519531  18398.759766  18374.000000   
2016-01-06  18469.380859  18064.300781  18410.570312  18191.320312   
2016-01-07  18172.039062  17767.339844  18139.769531  17767.339844   
2016-01-08  17975.310547  17509.640625  17562.230469  17697.960938   
...                  ...           ...           ...           ...   
2021-11-18  29715.949219  29402.570312  29597.929688  29598.660156   
2021-11-19  29768.539062  29589.189453  29641.050781  29745.869141   
2021-11-22  29806.490234  29542.289062  29618.550781  29774.109375   
2021-11-24  29758.050781  29212.929688  29663.449219  29302.660156   
2021-11-25  29570.419922  29444.449219  29469.650391  29499.279297   

                 Volume     Adj Close  Future Close  
Date                                                 
2016-01-04  140200000.0  18450.980469  18374.000000  
2016-01-05  132300000.0  18374.000000  18191.320312  
2016-01-06  142200000.0  18191.320312  17767.339844  
2016-01-07  168000000.0  17767.339844  17697.960938  
2016-01-08  184300000.0  17697.960938  17218.960938  
...                 ...           ...           ...  
2021-11-18   65400000.0  29598.660156  29745.869141  
2021-11-19   65600000.0  29745.869141  29774.109375  
2021-11-22   58800000.0  29774.109375  29302.660156  
2021-11-24   69500000.0  29302.660156  29499.279297  
2021-11-25          0.0  29499.279297           NaN  

[1441 rows x 7 columns]

In [36]:
target = computeTarget(n225['Close'], n225['Future Close'])

n225['Target'] = target
n225 = n225.dropna()

In [37]:
close = n225['Close']
high = n225['High']
low = n225['Low']
open = n225['Open']
volume  = n225['Volume']

In [38]:
n225_ti = pd.DataFrame()
n225_ti['SMA20'] = talib.SMA(close, timeperiod=20)
n225_ti['SMA50'] = talib.SMA(close, timeperiod=50)
n225_ti['SMA200'] = talib.SMA(close, timeperiod=200)
n225_ti['EMA'] = talib.EMA(close, timeperiod=14)
n225_ti['OBV'] = talib.OBV(close, volume)
n225_ti['RSI14'] = talib.RSI(close, timeperiod=14)
n225_ti['ADX'] = talib.ADX(high, low, close, timeperiod=14)
n225_ti['ADXR'] = talib.ADXR(high, low, close, timeperiod=14)
n225_ti['aroondown'], ti['aroonup'] = talib.AROON(high, low, timeperiod=14)
n225_ti['APO'] = talib.APO(close, fastperiod=12, slowperiod=26, matype=0)
n225_ti['AROONOSC'] = talib.AROONOSC(high, low, timeperiod=14)
n225_ti['BOP'] = talib.BOP(open, high, low, close)
n225_ti['CCI'] = talib.CCI(high, low, close, timeperiod=14)
n225_ti['CMO'] = talib.CMO(close, timeperiod=14)
n225_ti['DX'] = talib.DX(high, low, close, timeperiod=14)
n225_ti['macd'],ti['macdsignal'],ti['macdhist'] = talib.MACD(close, fastperiod = 12, slowperiod=26, signalperiod=9)
n225_ti['MFI'] = talib.MFI(high, low, close, volume, timeperiod=14)
n225_ti['MINUS_DI'] = talib.MINUS_DI(high, low, close, timeperiod=14)
n225_ti['MINUS_DM'] = talib.MINUS_DM(high, low, timeperiod=14)
n225_ti['MOM'] = talib.MOM(close, timeperiod=14)
n225_ti['PLUS_DI'] = talib.PLUS_DI(high, low, close, timeperiod=14)
n225_ti['PLUS_DM'] = talib.PLUS_DM(high, low, timeperiod=14)
n225_ti['PPO'] = talib.PPO(close, fastperiod=12, slowperiod=26, matype=0)
n225_ti['ROC'] = talib.ROC(close, timeperiod=10)
n225_ti['ROCP'] = talib.ROCP(close, timeperiod=10)
n225_ti['ROCR'] = talib.ROCR(close, timeperiod=10)
n225_ti['ROCR100'] = talib.ROCR100(close, timeperiod=10)
n225_ti['slowk'], ti['slowd'] = talib.STOCH(high, low, close, fastk_period=5, slowk_period=3, slowd_period=3, slowd_matype=0)
n225_ti['fastk'], ti['fastd'] = talib.STOCHF(high, low, close, fastk_period=5, fastd_period=3, fastd_matype=0)
n225_ti['TRIX'] = talib.TRIX(close, timeperiod=30)
n225_ti['ULTOSC'] = talib.ULTOSC(high, low, close, timeperiod1=7, timeperiod2=14, timeperiod3=28)
n225_ti['WILLR'] = talib.WILLR(high, low, close, timeperiod=14)
n225_ti['Target'] = n225['Target']
n225_ti

NameError: name 'ti' is not defined

In [ ]:
n225_ti = n225_ti.dropna()
X = n225_ti.drop("Target", axis=1)  # Feature Matrix
y = n225_ti["Target"]               # Target Variable

In [ ]:
model = LinearRegression()

#Initializing RFE model
rfe = RFE(model, n_features_to_select=7)

#Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

#Fitting the data to model
model.fit(X_rfe,y)

print(rfe.support_)
print(rfe.ranking_)

[False False False False False False False  True False False False  True
 False  True False False False  True False False False False False  True
 False False False False False  True  True False]
[17 19 25 16 26  7  2  1 11 12 14  1 13  1  8 15 18  1 24 22  5 23  3  1
 20 21  6 10  9  1  1  4]


In [ ]:
# no. of features
#
nof_list = np.arange(1, 13)            
high_score = 0

# Variable to store the optimum features
#
nof = 0           
score_list = []

for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.9, random_state = 0)

    model = LinearRegression()
    rfe = RFE(model, n_features_to_select=nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)

    score = model.score(X_test_rfe,y_test)
    score_list.append(score)

    if(score > high_score):
        high_score = score
        nof = nof_list[n]

print("Optimum number of features: %d" % nof)
print("Score with %d features: %f" % (nof, high_score))

Optimum number of features: 0
Score with 0 features: 0.000000


In [ ]:
cols = list(X.columns)
model = LinearRegression()

# Initializing RFE model
rfe = RFE(model, n_features_to_select=10)             

# Transforming data using RFE
X_rfe = rfe.fit_transform(X,y)  

# Fitting the data to model
model.fit(X_rfe,y)              
temp = pd.Series(rfe.support_, index = cols)
selected_features_rfe = temp[temp==True].index

print(selected_features_rfe)

Index(['ADX', 'ADXR', 'BOP', 'CMO', 'MINUS_DI', 'PPO', 'ROC', 'TRIX', 'ULTOSC',
       'WILLR'],
      dtype='object')


<h2>จากการทำ Feature Selection ควรจะใช้ 'ADX', 'ADXR', 'BOP', 'CMO', 'MINUS_DI', 'PPO', 'ROC', 'TRIX', 'ULTOSC',
       'WILLR' ในการสร้าง model</h2>

<h2>Decision Tree</h2>

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regress</h2>

<h2>Cauccian Process Regression</h2>

<h1>Heng Seng Index</h1>

<h2>Feature Selection</h2>

<h2>Decision Tree</h2>

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Gauccian Process Regression</h2>

<h1>SSE Composite Index</h1>

<h2>Feature Selection</h2>

<h2>Decision Tree</h2>

<h2>Random Forest</h2>

<h2>Logistic Regression</h2>

<h2>XGBoost</h2>

<h2>Linear Regression</h2>

<h2>Cauccian Process Regression</h2>